// Demonstration records only. Connect these fields to your college database before real use.
const students = [
 {id:'CSE2401',name:'Aarav Reddy',class:'CSE-A',marks:28,max:100,attendance:62,trend:[51,39,28],topics:[['Arrays',35],['Linked Lists',42],['Stacks & Queues',30]],assessments:[['Unit Test 1','28 / 100'],['Quiz 2','6 / 20'],['Assignment','5 / 10']],note:'Needs help with core concepts. Consider a short one-to-one revision session.',phone:'9876501201'},
 {id:'CSE2408',name:'Saanvi Kumar',class:'CSE-B',marks:34,max:100,attendance:71,trend:[58,46,34],topics:[['Arrays',45],['Linked Lists',38],['Stacks & Queues',52]],assessments:[['Unit Test 1','34 / 100'],['Quiz 2','8 / 20'],['Assignment','7 / 10']],note:'Review linked-list fundamentals and practice basic tracing questions.',phone:'9876501208'},
 {id:'CSE2415',name:'Rohit Naidu',class:'CSE-A',marks:39,max:100,attendance:68,trend:[55,48,39],topics:[['Arrays',55],['Linked Lists',40],['Stacks & Queues',47]],assessments:[['Unit Test 1','39 / 100'],['Quiz 2','9 / 20'],['Assignment','6 / 10']],note:'Marks are low and attendance needs follow-up.',phone:'9876501215'},
 {id:'CSE2422',name:'Divya Sharma',class:'CSE-C',marks:42,max:100,attendance:76,trend:[61,54,42],topics:[['Arrays',55],['Linked Lists',50],['Stacks & Queues',48]],assessments:[['Unit Test 1','42 / 100'],['Quiz 2','10 / 20'],['Assignment','7 / 10']],note:'Would benefit from more guided practice before the next test.',phone:'9876501222'},
 {id:'CSE2403',name:'Ishaan Varma',class:'CSE-A',marks:48,max:100,attendance:82,trend:[43,52,48],topics:[['Arrays',60],['Linked Lists',55],['Stacks & Queues',58]],assessments:[['Unit Test 1','48 / 100'],['Quiz 2','12 / 20'],['Assignment','7 / 10']],note:'Making progress. Encourage regular problem-solving practice.',phone:'9876501203'},
 {id:'CSE2410',name:'Nitya Rao',class:'CSE-B',marks:52,max:100,attendance:85,trend:[48,51,52],topics:[['Arrays',65],['Linked Lists',60],['Stacks & Queues',58]],assessments:[['Unit Test 1','52 / 100'],['Quiz 2','12 / 20'],['Assignment','8 / 10']],note:'Steady progress; continue weekly revision.',phone:'9876501210'},
 {id:'CSE2417',name:'Karthik Dev',class:'CSE-A',marks:56,max:100,attendance:79,trend:[64,60,56],topics:[['Arrays',68],['Linked Lists',60],['Stacks & Queues',62]],assessments:[['Unit Test 1','56 / 100'],['Quiz 2','13 / 20'],['Assignment','8 / 10']],note:'Can improve with more practice on linked lists.',phone:'9876501217'},
 {id:'CSE2424',name:'Ananya Das',class:'CSE-C',marks:59,max:100,attendance:88,trend:[58,61,59],topics:[['Arrays',70],['Linked Lists',62],['Stacks & Queues',66]],assessments:[['Unit Test 1','59 / 100'],['Quiz 2','14 / 20'],['Assignment','8 / 10']],note:'Good consistency. Focus on explaining solution complexity.',phone:'9876501224'},
 {id:'CSE2405',name:'Vikram Singh',class:'CSE-A',marks:72,max:100,attendance:91,topics:[['Arrays',82],['Linked Lists',72],['Stacks & Queues',78]],assessments:[['Unit Test 1','72 / 100'],['Quiz 2','16 / 20'],['Assignment','9 / 10']],note:'Performing well. Offer extension problems for deeper learning.',phone:'9876501205'},
 {id:'CSE2412',name:'Mira Joshi',class:'CSE-B',marks:81,max:100,attendance:94,topics:[['Arrays',90],['Linked Lists',82],['Stacks & Queues',85]],assessments:[['Unit Test 1','81 / 100'],['Quiz 2','18 / 20'],['Assignment','10 / 10']],note:'Strong understanding across current topics.',phone:'9876501212'},
 {id:'CSE2419',name:'Aditya Paul',class:'CSE-A',marks:88,max:100,attendance:96,topics:[['Arrays',92],['Linked Lists',88],['Stacks & Queues',90]],assessments:[['Unit Test 1','88 / 100'],['Quiz 2','19 / 20'],['Assignment','10 / 10']],note:'Excellent progress. Encourage peer learning if appropriate.',phone:'9876501219'},
 {id:'CSE2426',name:'Tara Ramesh',class:'CSE-C',marks:94,max:100,attendance:98,topics:[['Arrays',98],['Linked Lists',94],['Stacks & Queues',96]],assessments:[['Unit Test 1','94 / 100'],['Quiz 2','20 / 20'],['Assignment','10 / 10']],note:'Excellent performance and consistent attendance.',phone:'9876501226'}
];
const classSelect=document.getElementById('classSelect'),searchInput=document.getElementById('searchInput'),statusFilter=document.getElementById('statusFilter'),rows=document.getElementById('studentRows'),dialog=document.getElementById('studentDialog');
const band=s=>s.marks<40?'low':s.marks<70?'average':'good';
// Early warning: marks fell in both of the latest assessment intervals.
const hasEarlyWarning=s=>Array.isArray(s.trend)&&s.trend.length>=3&&s.trend[s.trend.length-3]>s.trend[s.trend.length-2]&&s.trend[s.trend.length-2]>s.trend[s.trend.length-1];
const label=s=>({low:'Needs support',average:'Making progress',good:'Doing well'}[band(s)]);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function getVisible(){const cls=classSelect.value,q=searchInput.value.trim().toLowerCase(),status=statusFilter.value;return students.filter(s=>(cls==='all'||s.class===cls)&&(!q||s.name.toLowerCase().includes(q)||s.id.toLowerCase().includes(q))&&(status==='all'||(status==='warning'?hasEarlyWarning(s):band(s)===status))).sort((a,b)=>(Number(hasEarlyWarning(b))-Number(hasEarlyWarning(a)))||({low:0,average:1,good:2}[band(a)]-{low:0,average:1,good:2}[band(b)])||a.marks-b.marks||a.name.localeCompare(b.name));}
function render(){const all=classSelect.value==='all'?students:students.filter(s=>s.class===classSelect.value);document.getElementById('totalCount').textContent=all.length;document.getElementById('lowCount').textContent=all.filter(s=>band(s)==='low').length;document.getElementById('averageCount').textContent=all.filter(s=>band(s)==='average').length;document.getElementById('goodCount').textContent=all.filter(s=>band(s)==='good').length;const data=getVisible();rows.innerHTML=data.length?data.map(s=>`<tr class="status-${band(s)}" data-id="${s.id}" tabindex="0" aria-label="View ${esc(s.name)} details"><td data-label="STUDENT"><div class="student-cell"><span class="student-avatar">${esc(s.name.split(' ').map(n=>n[0]).slice(0,2).join(''))}</span><span><b class="student-name">${esc(s.name)}</b><small class="student-id">${esc(s.id)}${hasEarlyWarning(s)?' · <span class="warning-text">↓ Early warning</span>':''}</small></span></div></td><td data-label="CLASS">${esc(s.class)}</td><td data-label="LAST MARKS"><span class="mark">${s.marks}<small> / ${s.max}</small></span></td><td data-label="SUBJECT ATTENDANCE"><span class="attendance ${s.attendance<75?'low-attendance':''}"><span class="attendance-track"><span style="width:${s.attendance}%"></span></span><em>${s.attendance}%</em></span></td><td data-label="STATUS"><span class="status-pill ${band(s)}">${label(s)}</span>${hasEarlyWarning(s)?'<small class="warning-chip">Marks falling</small>':''}</td><td data-label="DETAILS"><a href="#student-${s.id}" class="open-link" data-open="${s.id}">View details ↗</a></td></tr>`).join(''):'<tr><td colspan="6" class="empty-row">No students match these filters.</td></tr>';}
function showDetail(id){const s=students.find(x=>x.id===id);if(!s)return;const cls=band(s);document.getElementById('studentDetail').innerHTML=`<div class="detail-head"><span class="detail-avatar">${esc(s.name.split(' ').map(n=>n[0]).slice(0,2).join(''))}</span><div><h2>${esc(s.name)}</h2><p>${esc(s.id)} · ${esc(s.class)} · Data Structures & Algorithms</p></div></div><div class="detail-band"><div><small>Latest subject mark</small><strong style="color:var(--${cls==='low'?'red':cls==='average'?'yellow':'green'})">${s.marks} / ${s.max}</strong></div><span class="status-pill ${cls}">${label(s)}</span></div><div class="detail-grid"><div class="detail-metric"><small>Subject attendance</small><b>${s.attendance}%</b></div><div class="detail-metric"><small>Topics tracked</small><b>${s.topics.length}</b></div><div class="detail-metric"><small>Assessments recorded</small><b>${s.assessments.length}</b></div></div>${hasEarlyWarning(s)?`<div class="early-warning-box"><b>Early warning · Marks are declining</b><p>The latest three assessment scores show a continuous drop (${s.trend.join(' → ')}). Consider checking in with the student and reviewing difficult topics.</p></div>`:''}<h3 class="detail-section-title">Assessment history</h3>${s.assessments.map(a=>`<div class="assessment-row"><span>${esc(a[0])}</span><b>${esc(a[1])}</b></div>`).join('')}<h3 class="detail-section-title">Topic-wise progress</h3>${s.topics.map(t=>`<div class="topic-row"><span>${esc(t[0])}</span><span>${t[1]}% completed</span></div>`).join('')}<h3 class="detail-section-title">Teacher follow-up note</h3><p class="detail-note">${esc(s.note)}</p><div class="detail-actions"><a class="action-btn" href="tel:${s.phone}">Contact student</a><button class="action-btn" id="copyStudent">Copy student ID</button></div><p class="detail-note">Phone: ${esc(s.phone)} · Sample number for demonstration. In production, show contact details only to authorized staff.</p>`;dialog.showModal();document.getElementById('copyStudent').addEventListener('click',()=>{const btn=document.getElementById('copyStudent');btn.textContent='Student ID: '+s.id;});}
rows.addEventListener('click',e=>{const row=e.target.closest('tr[data-id]');if(row)showDetail(row.dataset.id);});rows.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('tr[data-id]')){e.preventDefault();showDetail(e.target.dataset.id);}});[classSelect,searchInput,statusFilter].forEach(el=>el.addEventListener(el===searchInput?'input':'change',render));document.getElementById('closeDialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});render();
